
name: Finish Release
env:
  RELEASE_NAME: ${{ github.event.release.tag_name }}
on:
  release:
    types: [published]
jobs:
  complete_release:
    runs-on: ubuntu-latest
    steps:
      - name: Print Releae Title
        run: echo "Release $RELEASE_NAME"
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            "ghcr.io/michaelmelody91/hello-world:${{ github.event.release.tag_name }}"
      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
          ref: main
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "release/${{ github.event.release.tag_name }}"
          destination_branch: "main"
          pr_title: "Pulling ${{ github.ref }} into master"
          pr_body: ":crown: *An automated PR*"             
          pr_draft: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
