name: Complete Release
env:
  RELEASE_NAME: ${{ github.event.release.tag_name }}
on: [release]
jobs:
  start_release:
    runs-on: ubuntu-latest
    steps:
      - name: Print Releae Title
        run: echo "Release $RELEASE_NAME"
