
name: Finish Release
env:
  RELEASE_NAME: ${{ github.event.release.tag_name }}
on:
  release:
    types: [published]
jobs:
  complete_release:
    runs-on: ubuntu-latest
    steps:
      - name: Print Releae Title
        run: echo "Release $RELEASE_NAME"
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            "ghcr.io/michaelmelody91/hello-world:${{ github.event.release.tag_name }}"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.CR_PAT }}
          commit-message: Complete Release
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: "release/${{ github.event.release.tag_name }}"
          delete-branch: true
          title: '${{ github.event.release.tag_name }} -> main'
          base: main
