name: CI
on:
  workflow_dispatch:
    inputs:
      release_name:
        description: 'Release name'
        required: true
jobs:
  start_release:
    runs-on: ubuntu-latest
    steps:
      - name: Print Releae Title
        run: echo "Release ${{ github.event.inputs.release_name }}"
      - name: Create Release Branch
        uses: actions/checkout@v2
        with:
          ref: "release/${{ github.event.inputs.release_name }}"
