name: CI
on:
  workflow_dispatch:
    inputs:
    release_name:
      description: 'Release name'
      required: true
jobs:
  start_release:
    runs-on: ubuntu-latest
    steps:
      - name: Print Releae Title
        run: echo "Release $INPUT_RELEASE_NAME"
